//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

	export interface JsonSummaryResult
	{
		summary: JsonCoverageSummary;
		coverage: JsonCoverageCoverage;
	}
	type Nullable<T> = T | null
	export interface JsonCoverageSummary
	{
		generatedon: Date;
		parser: string;
		assemblies: number;
		classes: number;
		files: number;
		coveredlines: number;
		uncoveredlines: number;
		coverablelines: number;
		totallines: number;
		linecoverage: Nullable<number>;
		coveredbranches: Nullable<number>;
		totalbranches: Nullable<number>;
		branchcoverage: Nullable<number>;
	}
	export interface JsonCoverageCoverage
	{
		assemblies: JsonAssemblyCoverage[];
	}
	export interface JsonAssemblyCoverage
	{
		name: string;
		classes: number;
		coveredlines: number;
		coverablelines: number;
		totallines: Nullable<number>;
		coverage: Nullable<number>;
		coveredbranches: Nullable<number>;
		totalbranches: Nullable<number>;
		branchcoverage: Nullable<number>;
		classesinassembly: JsonClassCoverage[];
	}
	export interface JsonClassCoverage
	{
		name: string;
		coveredlines: number;
		uncoveredlines: number;
		coverablelines: number;
		totallines: Nullable<number>;
		coverage: Nullable<number>;
		coveredbranches: Nullable<number>;
		totalbranches: Nullable<number>;
		branchcoverage: Nullable<number>;
	}
