import { JsonSummaryResult } from "./jsonSummaryResult";

function getJsonSummary(): JsonSummaryResult {
    // todo
    return {
        summary: {
            assemblies:2,
            classes:10,
            branchcoverage:0.5,
            coveredbranches:5,
            totalbranches:10,

            coveredlines:2,
            coverablelines:20,
            uncoveredlines:18,
            linecoverage:0.1,
            totallines:30,

            files:3,
            parser:"Cobertura",
            generatedon:new Date(),
        },
        coverage:{
            assemblies:[
                {
                    name:"Assembly1",
                    classesinassembly:[
                        {
                            name:"Ns.Class1",
                            branchcoverage:0,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:2,
                            coveredlines:1,
                            coverage:1,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Ns.Class2",
                            branchcoverage:0,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:2,
                            coveredlines:2,
                            coverage:0.8,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Ns2.Class1",
                            branchcoverage:0,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:4,
                            coveredlines:3,
                            coverage:0.6,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Ns2.Class2",
                            branchcoverage:0,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:5,
                            coveredlines:4,
                            coverage:0.4,
                            totallines:0,
                            uncoveredlines:0
                        }
                    ],
                    branchcoverage:0,
                    classes:2,
                    coverablelines:0,
                    coveredlines:0,
                    totallines:0,
                    coverage:0,
                    coveredbranches:0,
                    totalbranches:0
                },
                {
                    name:"Assembly2",
                    classesinassembly:[
                        {
                            name:"Ns.Class1",
                            branchcoverage:null,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:6,
                            coveredlines:5,
                            coverage:0.33333333333333,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Ns.Class2",
                            branchcoverage:0.5,
                            coveredbranches:1,
                            totalbranches:2,
                            coverablelines:7,
                            coveredlines:6,
                            coverage:0.2,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Ns2.Class1",
                            branchcoverage:0.333333,
                            coveredbranches:1,
                            totalbranches:3,
                            coverablelines:8,
                            coveredlines:7,
                            coverage:0.1,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Ns2.Class2",
                            branchcoverage:0,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:9,
                            coveredlines:8,
                            coverage:0,
                            totallines:0,
                            uncoveredlines:0
                        },
                        {
                            name:"Other",
                            branchcoverage:0,
                            coveredbranches:0,
                            totalbranches:0,
                            coverablelines:9,
                            coveredlines:8,
                            coverage:0,
                            totallines:0,
                            uncoveredlines:0
                        }
                    ],
                    branchcoverage:0,
                    classes:2,
                    coverablelines:0,
                    coveredlines:0,
                    totallines:0,
                    coverage:0,
                    coveredbranches:0,
                    totalbranches:0
                }
            ]
        }
    }
}

export {getJsonSummary}