//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

	export interface JsonSummaryResult {
		summary: JsonCoverageSummary;
		coverage: JsonCoverageCoverage;
	}
	export interface JsonCoverageSummary {
		generatedon: Date;
		parser: string;
		assemblies: number;
		classes: number;
		files: number;
		coveredlines: number;
		uncoveredlines: number;
		coverablelines: number;
		totallines: number;
		/** Nullable */
		linecoverage: number;
		coveredbranches: number;
		totalbranches: number;
		/** Nullable */
		branchcoverage: number;
	}
	export interface JsonCoverageCoverage {
		assemblies: JsonAssemblyCoverage[];
	}
	export interface JsonAssemblyCoverage {
		name: string;
		classes: number;
		coveredlines: number;
		coverablelines: number;
		totallines: number;
		/** Nullable */
		coverage: number;
		coveredbranches: number;
		totalbranches: number;
		/** Nullable */
		branchcoverage: number;
		classesinassembly: JsonClassCoverage[];
	}
	export interface JsonClassCoverage {
		name: string;
		coveredlines: number;
		uncoveredlines: number;
		coverablelines: number;
		totallines: number;
		/** Nullable */
		coverage: number;
		coveredbranches: number;
		totalbranches: number;
		/** Nullable */
		branchcoverage: number;
	}
