//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module Json_Report_Generator_To_Html.JsonSummary {
	export interface IJsonSummaryResult
	{
		summary: Json_Report_Generator_To_Html.JsonSummary.IJsonCoverageSummary;
		coverage: Json_Report_Generator_To_Html.JsonSummary.IJsonCoverageCoverage;
	}
	export interface IJsonCoverageSummary
	{
		generatedon: Date;
		parser: string;
		assemblies: number;
		classes: number;
		files: number;
		coveredlines: number;
		uncoveredlines: number;
		coverablelines: number;
		totallines: number;
		/** Nullable */
		linecoverage: number;
		coveredbranches: number;
		totalbranches: number;
		/** Nullable */
		branchcoverage: number;
	}
	export interface IJsonCoverageCoverage
	{
		assemblies: Json_Report_Generator_To_Html.JsonSummary.IJsonAssemblyCoverage[];
	}
	export interface IJsonAssemblyCoverage
	{
		name: string;
		classes: number;
		coveredlines: number;
		coverablelines: number;
		totallines: number;
		/** Nullable */
		coverage: number;
		coveredbranches: number;
		totalbranches: number;
		/** Nullable */
		branchcoverage: number;
		classesinassembly: Json_Report_Generator_To_Html.JsonSummary.IJsonClassCoverage[];
	}
	export interface IJsonClassCoverage
	{
		name: string;
		coveredlines: number;
		uncoveredlines: number;
		coverablelines: number;
		totallines: number;
		/** Nullable */
		coverage: number;
		coveredbranches: number;
		totalbranches: number;
		/** Nullable */
		branchcoverage: number;
	}
}
